using System.Text;

namespace SQLVisualExplorer.UI.ViewModels;

internal static class CompareHtmlExporter
{
    public static string Generate(
        string sqlA, string sqlB,
        ComparePlanResultViewModel? resultA,
        ComparePlanResultViewModel? resultB,
        IEnumerable<PlanNodeVisualItemViewModel> nodesA,
        IEnumerable<PlanNodeVisualItemViewModel> nodesB)
    {
        var sb = new StringBuilder();
        sb.AppendLine("<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\">");
        sb.AppendLine("<title>SQL Query Comparison Report</title><style>");
        sb.AppendLine(Css);
        sb.AppendLine("</style></head><body>");
        sb.AppendLine("<h1>Query Comparison Report</h1>");
        sb.AppendLine($"<p class=\"ts\">Generated by SQL Visual Explorer · {DateTime.Now:yyyy-MM-dd HH:mm}</p>");
        sb.AppendLine("<div class=\"side-by-side\">");
        AppendSection(sb, "Query A", sqlA, resultA, nodesA);
        AppendSection(sb, "Query B", sqlB, resultB, nodesB);
        sb.AppendLine("</div></body></html>");
        return sb.ToString();
    }

    private static void AppendSection(
        StringBuilder sb, string label, string sql,
        ComparePlanResultViewModel? result,
        IEnumerable<PlanNodeVisualItemViewModel> nodes)
    {
        var cls = result?.IsWinner == true ? " winner" : "";
        sb.AppendLine($"<div class=\"col{cls}\"><h2>{label}{(result?.IsWinner == true ? " 🏆" : "")}</h2>");
        sb.AppendLine($"<pre class=\"sql\">{Escape(sql)}</pre>");
        if (result is not null)
        {
            sb.AppendLine("<table class=\"m\"><tbody>");
            sb.AppendLine($"<tr><td>Time</td><td>{Escape(result.TimeText)}</td></tr>");
            sb.AppendLine($"<tr><td>Cost</td><td>{Escape(result.CostText)}</td></tr>");
            sb.AppendLine($"<tr><td>Est. rows</td><td>{Escape(result.EstRowsText)}</td></tr>");
            sb.AppendLine($"<tr><td>Act. rows</td><td>{Escape(result.ActRowsText)}</td></tr>");
            sb.AppendLine($"<tr><td>Nodes</td><td>{Escape(result.NodeCountText)}</td></tr>");
            sb.AppendLine($"<tr><td>Issues</td><td style=\"color:{result.IssueColor}\">{Escape(result.IssueText)}</td></tr>");
            sb.AppendLine("</tbody></table>");
        }
        sb.AppendLine("<h3>Plan Nodes</h3><table><thead><tr><th>Operation</th><th>Cost</th><th>Time</th><th></th></tr></thead><tbody>");
        foreach (var n in nodes)
            sb.AppendLine($"<tr><td style=\"padding-left:{n.TreeIndentMargin.Left + 6}px\">{Escape(n.Label)}</td><td>{Escape(n.CostCell)}</td><td>{Escape(n.TimeCell)}</td><td style=\"color:{n.IssueColor}\">{Escape(n.IssueGlyph)}</td></tr>");
        sb.AppendLine("</tbody></table></div>");
    }

    private static string Escape(string? s) =>
        (s ?? string.Empty).Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;").Replace("\"", "&quot;");

    private const string Css = @"
body{background:#101418;color:#E7ECEF;font-family:system-ui,sans-serif;padding:24px;margin:0}
h1{color:#80B8FF;border-bottom:1px solid #26313A;padding-bottom:8px}
h2{margin:0 0 10px;font-size:16px}h3{font-size:13px;color:#91A0AD;margin:12px 0 6px}
.side-by-side{display:grid;grid-template-columns:1fr 1fr;gap:20px}
.col{background:#141A20;border:1px solid #26313A;border-radius:8px;padding:16px}
.col.winner{border-color:#80B8FF}
pre.sql{background:#0A0F13;border:1px solid #26313A;padding:10px;border-radius:5px;font-size:12px;overflow-x:auto;color:#7BD88F;white-space:pre-wrap}
table{width:100%;border-collapse:collapse;font-size:12px;margin-bottom:10px}
table.m td:first-child{color:#91A0AD;width:90px}
th{text-align:left;padding:6px 8px;background:#0F1419;color:#6F7E89;border-bottom:1px solid #26313A}
td{padding:5px 8px;border-bottom:1px solid #1A222A;font-family:monospace}
.ts{font-size:11px;color:#4A5A66;margin:-8px 0 16px}
";
}
