using System.Text;

namespace SQLVisualExplorer.UI.ViewModels;

internal static class PlanHtmlExporter
{
    public static string Generate(
        string sqlText,
        IEnumerable<PlanNodeVisualItemViewModel> nodes,
        IEnumerable<PlanIssueItemViewModel> issues,
        string summary)
    {
        var sb = new StringBuilder();
        sb.AppendLine("<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\">");
        sb.AppendLine("<title>SQL Execution Plan</title><style>");
        sb.AppendLine(Css);
        sb.AppendLine("</style></head><body>");
        sb.AppendLine("<h1>SQL Execution Plan</h1>");
        sb.AppendLine("<h2>Query</h2>");
        sb.AppendLine($"<pre class=\"sql\">{Escape(sqlText)}</pre>");
        sb.AppendLine("<h2>Summary</h2>");
        sb.AppendLine($"<pre class=\"summary\">{Escape(summary)}</pre>");
        sb.AppendLine("<h2>Plan Nodes</h2>");
        sb.AppendLine("<table><thead><tr><th>Operation</th><th>Cost</th><th>Rows</th><th>Time</th><th>Issues</th></tr></thead><tbody>");
        foreach (var node in nodes)
        {
            var rowClass = node.IssueText is "Critical" or "Warning"
                ? $" class=\"{node.IssueText.ToLowerInvariant()}\""
                : "";
            sb.AppendLine($"<tr{rowClass}><td style=\"padding-left:{node.TreeIndentMargin.Left + 8}px\">{Escape(node.Label)}</td><td>{Escape(node.CostCell)}</td><td>{Escape(node.RowsCell)}</td><td>{Escape(node.TimeCell)}</td><td style=\"color:{node.IssueColor}\">{Escape(node.IssueGlyph)} {Escape(node.IssueText)}</td></tr>");
        }
        sb.AppendLine("</tbody></table>");

        var issueList = issues.ToList();
        if (issueList.Count > 0)
        {
            sb.AppendLine("<h2>Issues</h2><ul class=\"issues\">");
            foreach (var issue in issueList)
                sb.AppendLine($"<li class=\"{issue.Severity.ToLowerInvariant()}\"><strong>{Escape(issue.Title)}</strong> <span class=\"code\">{Escape(issue.Code)}</span><p>{Escape(issue.Description)}</p><p class=\"rec\">{Escape(issue.Recommendation)}</p></li>");
            sb.AppendLine("</ul>");
        }

        sb.AppendLine($"<footer>Generated by SQL Visual Explorer · {DateTime.Now:yyyy-MM-dd HH:mm}</footer>");
        sb.AppendLine("</body></html>");
        return sb.ToString();
    }

    private static string Escape(string? s) =>
        (s ?? string.Empty)
            .Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;")
            .Replace("\"", "&quot;");

    private const string Css = @"
body{background:#101418;color:#E7ECEF;font-family:system-ui,sans-serif;padding:32px;max-width:1100px;margin:0 auto}
h1,h2{color:#80B8FF;border-bottom:1px solid #26313A;padding-bottom:6px}
pre{background:#0A0F13;border:1px solid #26313A;padding:12px;border-radius:6px;overflow-x:auto;font-size:13px}
pre.sql{color:#7BD88F}pre.summary{color:#91A0AD}
table{width:100%;border-collapse:collapse;font-size:13px}
th{text-align:left;padding:8px 10px;background:#141A20;color:#91A0AD;border-bottom:1px solid #26313A}
td{padding:6px 10px;border-bottom:1px solid #1A222A;font-family:monospace}
tr.warning td{background:#1A1800}tr.critical td{background:#1A0808}
ul.issues{list-style:none;padding:0}
ul.issues li{margin-bottom:12px;padding:12px;background:#141A20;border:1px solid #26313A;border-radius:6px}
ul.issues li.critical{border-left:3px solid #FF8A7A}
ul.issues li.warning{border-left:3px solid #FFD166}
ul.issues li.info{border-left:3px solid #80B8FF}
.code{font-size:11px;color:#6F7E89;margin-left:8px}
p{margin:6px 0;font-size:13px}p.rec{color:#91A0AD}
footer{margin-top:32px;font-size:11px;color:#4A5A66;border-top:1px solid #26313A;padding-top:12px}
";
}
