// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SQLVisualExplorer.Infrastructure.Database;

#nullable disable

namespace SQLVisualExplorer.Infrastructure.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.16");

            modelBuilder.Entity("SQLVisualExplorer.Infrastructure.Database.Entities.ComparisonEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("QueryA")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("query_a");

                    b.Property<string>("QueryB")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("query_b");

                    b.Property<string>("ResultJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("result_json");

                    b.HasKey("Id");

                    b.ToTable("comparisons", (string)null);
                });

            modelBuilder.Entity("SQLVisualExplorer.Infrastructure.Database.Entities.ConnectionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Database")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("database");

                    b.Property<string>("DatabaseType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("db_type");

                    b.Property<string>("Host")
                        .HasColumnType("TEXT")
                        .HasColumnName("host");

                    b.Property<DateTime?>("LastUsed")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_used");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int?>("Port")
                        .HasColumnType("INTEGER")
                        .HasColumnName("port");

                    b.Property<bool>("UseSsl")
                        .HasColumnType("INTEGER")
                        .HasColumnName("use_ssl");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("connections", (string)null);
                });

            modelBuilder.Entity("SQLVisualExplorer.Infrastructure.Database.Entities.QueryHistoryEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ConnectionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("connection_id");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("executed_at");

                    b.Property<string>("ExplainJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("explain_json");

                    b.Property<long?>("RowCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("row_count");

                    b.Property<string>("SqlText")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("sql_text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId");

                    b.ToTable("query_history", (string)null);
                });

            modelBuilder.Entity("SQLVisualExplorer.Infrastructure.Database.Entities.SnippetEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("SqlText")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("sql_text");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT")
                        .HasColumnName("tags");

                    b.HasKey("Id");

                    b.ToTable("snippets", (string)null);
                });

            modelBuilder.Entity("SQLVisualExplorer.Infrastructure.Database.Entities.QueryHistoryEntity", b =>
                {
                    b.HasOne("SQLVisualExplorer.Infrastructure.Database.Entities.ConnectionEntity", "Connection")
                        .WithMany("QueryHistory")
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Connection");
                });

            modelBuilder.Entity("SQLVisualExplorer.Infrastructure.Database.Entities.ConnectionEntity", b =>
                {
                    b.Navigation("QueryHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
